# Copyright (c) 2026 NightWorksIO
"""Every tool the server offers, as the contract describes it.

Generated from the contract lemonfiber 0e9fbff3d7b423c54967af31b0b77d083e37b0a0 published, vendored in `contract/web-api/`.
Do not edit: `just generate` rewrites it, and CI fails on any difference.
"""

from typing import Final

from lemonfiber_mcp.shapes import Reach, ToolShape

API_VERSION: Final = 1
"""The `api_version` the tools were generated for."""

CONTRACT: Final = '0e9fbff3d7b423c54967af31b0b77d083e37b0a0'
"""The lemonfiber revision whose contract the tools were generated from."""

TOOLS: Final[tuple[ToolShape, ...]] = (
    ToolShape(
        name='read_version',
        reach=Reach.READ,
        target='version',
        capability='/api/version',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/version',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_forms',
        reach=Reach.READ,
        target='forms',
        capability='/api/forms',
        parameters=('form',),
        input_schema={'type': 'object',
                      'properties': {'form': {'type': 'array', 'items': {'type': 'string'}}},
                      'additionalProperties': False},
        resource='lemonfiber://read/forms{?form*}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_status',
        reach=Reach.READ,
        target='status',
        capability='/api/status',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/status',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_services',
        reach=Reach.READ,
        target='services',
        capability='/api/services',
        parameters=('form',),
        input_schema={'type': 'object',
                      'properties': {'form': {'type': 'array', 'items': {'type': 'string'}}},
                      'additionalProperties': False},
        resource='lemonfiber://read/services{?form*}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_checks',
        reach=Reach.READ,
        target='checks',
        capability='/api/checks',
        parameters=('only',),
        input_schema={'type': 'object', 'properties': {'only': {'type': 'string'}}, 'additionalProperties': False},
        resource='lemonfiber://read/checks{?only}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_storage',
        reach=Reach.READ,
        target='storage',
        capability='/api/storage',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/storage',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_requests',
        reach=Reach.READ,
        target='requests',
        capability='/api/requests',
        parameters=('member', 'defaults'),
        input_schema={'type': 'object',
                      'properties': {'member': {'type': 'string'}, 'defaults': {'type': 'string'}},
                      'additionalProperties': False},
        resource='lemonfiber://read/requests{?member,defaults}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_held',
        reach=Reach.READ,
        target='held',
        capability='/api/held',
        parameters=('member', 'defaults', 'most'),
        input_schema={'type': 'object',
                      'properties': {'member': {'type': 'string'},
                                     'defaults': {'type': 'string'},
                                     'most': {'type': 'string'}},
                      'additionalProperties': False},
        resource='lemonfiber://read/held{?member,defaults,most}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_held_by_id',
        reach=Reach.READ,
        target='held/{id}',
        capability='/api/held/{id}',
        parameters=('id', 'member', 'defaults'),
        input_schema={'type': 'object',
                      'properties': {'id': {'type': 'string'},
                                     'member': {'type': 'string'},
                                     'defaults': {'type': 'string'}},
                      'required': ['id'],
                      'additionalProperties': False},
        resource='lemonfiber://read/held/{id}{?member,defaults}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_watching',
        reach=Reach.READ,
        target='watching',
        capability='/api/watching',
        parameters=('member', 'most'),
        input_schema={'type': 'object',
                      'properties': {'member': {'type': 'string'}, 'most': {'type': 'string'}},
                      'additionalProperties': False},
        resource='lemonfiber://read/watching{?member,most}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_playing',
        reach=Reach.READ,
        target='playing',
        capability='/api/playing',
        parameters=('member',),
        input_schema={'type': 'object', 'properties': {'member': {'type': 'string'}}, 'additionalProperties': False},
        resource='lemonfiber://read/playing{?member}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_hosting',
        reach=Reach.READ,
        target='hosting',
        capability='/api/hosting',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/hosting',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_front_door',
        reach=Reach.READ,
        target='front-door',
        capability='/api/front-door',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/front-door',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_news',
        reach=Reach.READ,
        target='news',
        capability='/api/news',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/news',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_trace',
        reach=Reach.READ,
        target='trace',
        capability='/api/trace',
        parameters=('term', 'season'),
        input_schema={'type': 'object',
                      'properties': {'term': {'type': 'string'}, 'season': {'type': 'string'}},
                      'additionalProperties': False},
        resource='lemonfiber://read/trace{?term,season}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_stuck',
        reach=Reach.READ,
        target='stuck',
        capability='/api/stuck',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/stuck',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_config',
        reach=Reach.READ,
        target='config',
        capability='/api/config',
        parameters=('key',),
        input_schema={'type': 'object', 'properties': {'key': {'type': 'string'}}, 'additionalProperties': False},
        resource='lemonfiber://read/config{?key}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_quality',
        reach=Reach.READ,
        target='quality',
        capability='/api/quality',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/quality',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_explain',
        reach=Reach.READ,
        target='explain',
        capability='/api/explain',
        parameters=('word',),
        input_schema={'type': 'object', 'properties': {'word': {'type': 'string'}}, 'additionalProperties': False},
        resource='lemonfiber://read/explain{?word}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_backups',
        reach=Reach.READ,
        target='backups',
        capability='/api/backups',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/backups',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_outbound',
        reach=Reach.READ,
        target='outbound',
        capability='/api/outbound',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/outbound',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_provenance',
        reach=Reach.READ,
        target='provenance',
        capability='/api/provenance',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/provenance',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_catalogue',
        reach=Reach.READ,
        target='catalogue',
        capability='/api/catalogue',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/catalogue',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_stored',
        reach=Reach.READ,
        target='stored',
        capability='/api/stored',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/stored',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_uninstall',
        reach=Reach.READ,
        target='uninstall',
        capability='/api/uninstall',
        parameters=('tier',),
        input_schema={'type': 'object', 'properties': {'tier': {'type': 'string'}}, 'additionalProperties': False},
        resource='lemonfiber://read/uninstall{?tier}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_space',
        reach=Reach.READ,
        target='space',
        capability='/api/space',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/space',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_bandwidth',
        reach=Reach.READ,
        target='bandwidth',
        capability='/api/bandwidth',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/bandwidth',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_clients',
        reach=Reach.READ,
        target='clients',
        capability='/api/clients',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/clients',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_alerts',
        reach=Reach.READ,
        target='alerts',
        capability='/api/alerts',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/alerts',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_credentials',
        reach=Reach.READ,
        target='credentials',
        capability='/api/credentials',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/credentials',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_migration',
        reach=Reach.READ,
        target='migration',
        capability='/api/migration',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/migration',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_history',
        reach=Reach.READ,
        target='history',
        capability='/api/history',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/history',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_update',
        reach=Reach.READ,
        target='update',
        capability='/api/update',
        parameters=('what', 'to'),
        input_schema={'type': 'object',
                      'properties': {'what': {'type': 'string'}, 'to': {'type': 'string'}},
                      'additionalProperties': False},
        resource='lemonfiber://read/update{?what,to}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_plugins',
        reach=Reach.READ,
        target='plugins',
        capability='/api/plugins',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/plugins',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_wiring',
        reach=Reach.READ,
        target='wiring',
        capability='/api/wiring',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'additionalProperties': False},
        resource='lemonfiber://read/wiring',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_logs',
        reach=Reach.LOGS,
        target='logs',
        capability='/api/logs',
        parameters=('form', 'service', 'tail'),
        input_schema={'type': 'object',
                      'properties': {'form': {'type': 'array', 'items': {'type': 'string'}},
                                     'service': {'type': 'array', 'items': {'type': 'string'}},
                                     'tail': {'type': 'string'}},
                      'additionalProperties': False},
        resource='lemonfiber://read/logs{?form*,service*,tail}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_bundle',
        reach=Reach.FILE,
        target='bundle/{name}',
        capability='/api/bundle/{name}',
        parameters=('name',),
        input_schema={'type': 'object',
                      'properties': {'name': {'type': 'string'}},
                      'required': ['name'],
                      'additionalProperties': False},
        resource='lemonfiber://bundle/{name}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_held_poster',
        reach=Reach.FILE,
        target='held/{id}/poster',
        capability='/api/held/{id}/poster',
        parameters=('id', 'member', 'defaults'),
        input_schema={'type': 'object',
                      'properties': {'id': {'type': 'string'},
                                     'member': {'type': 'string'},
                                     'defaults': {'type': 'string'}},
                      'required': ['id'],
                      'additionalProperties': False},
        resource='lemonfiber://held/{id}/poster{?member,defaults}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='read_held_backdrop',
        reach=Reach.FILE,
        target='held/{id}/backdrop',
        capability='/api/held/{id}/backdrop',
        parameters=('id', 'member', 'defaults'),
        input_schema={'type': 'object',
                      'properties': {'id': {'type': 'string'},
                                     'member': {'type': 'string'},
                                     'defaults': {'type': 'string'}},
                      'required': ['id'],
                      'additionalProperties': False},
        resource='lemonfiber://held/{id}/backdrop{?member,defaults}',
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='rehearse_restart',
        reach=Reach.REHEARSAL,
        target='restart',
        capability='/api/actions/restart',
        parameters=('forms', 'services'),
        input_schema={'type': 'object',
                      'properties': {'forms': {'default': [],
                                               'description': 'The forms to act on.',
                                               'items': {'type': 'string'},
                                               'type': 'array'},
                                     'services': {'default': [],
                                                  'description': 'The services to act on, leaving the rest of the form '
                                                                 'alone.',
                                                  'items': {'type': 'string'},
                                                  'type': 'array'}},
                      'required': [],
                      'additionalProperties': False},
        resource=None,
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='restart',
        reach=Reach.ACTION,
        target='restart',
        capability='/api/actions/restart',
        parameters=('forms', 'services', 'offer'),
        input_schema={'type': 'object',
                      'properties': {'forms': {'default': [],
                                               'description': 'The forms to act on.',
                                               'items': {'type': 'string'},
                                               'type': 'array'},
                                     'services': {'default': [],
                                                  'description': 'The services to act on, leaving the rest of the form '
                                                                 'alone.',
                                                  'items': {'type': 'string'},
                                                  'type': 'array'},
                                     'offer': {'type': 'string'}},
                      'required': ['offer'],
                      'additionalProperties': False},
        resource=None,
        read_only=False,
        destructive=True,
        idempotent=True,
    ),
    ToolShape(
        name='diagnose',
        reach=Reach.ACTION,
        target='diagnose',
        capability='/api/actions/diagnose',
        parameters=('only', 'disruptive'),
        input_schema={'type': 'object',
                      'properties': {'only': {'default': None,
                                              'description': 'The group of checks, or the one check, a diagnosis is '
                                                             'narrowed to.',
                                              'type': ['string', 'null']},
                                     'disruptive': {'default': False,
                                                    'description': 'Whether the checks that disturb the running system '
                                                                   'are included.',
                                                    'type': 'boolean'}},
                      'required': [],
                      'additionalProperties': False},
        resource=None,
        read_only=False,
        destructive=True,
        idempotent=False,
    ),
    ToolShape(
        name='rehearse_update',
        reach=Reach.REHEARSAL,
        target='update',
        capability='/api/actions/update',
        parameters=('wait', 'service'),
        input_schema={'type': 'object',
                      'properties': {'wait': {'default': False,
                                              'description': 'Whether anything still downloading is let finish before '
                                                             'the stop.',
                                              'type': 'boolean'},
                                     'service': {'default': None,
                                                 'description': 'The one service to act on instead of the whole stack.',
                                                 'type': ['string', 'null']}},
                      'required': [],
                      'additionalProperties': False},
        resource=None,
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='update',
        reach=Reach.ACTION,
        target='update',
        capability='/api/actions/update',
        parameters=('wait', 'service', 'offer', 'confirm'),
        input_schema={'type': 'object',
                      'properties': {'wait': {'default': False,
                                              'description': 'Whether anything still downloading is let finish before '
                                                             'the stop.',
                                              'type': 'boolean'},
                                     'service': {'default': None,
                                                 'description': 'The one service to act on instead of the whole stack.',
                                                 'type': ['string', 'null']},
                                     'offer': {'type': 'string'},
                                     'confirm': {'default': False,
                                                 'description': 'Whether a cost the action would incur was agreed to in '
                                                                'advance.',
                                                 'type': 'boolean'}},
                      'required': ['offer'],
                      'additionalProperties': False},
        resource=None,
        read_only=False,
        destructive=True,
        idempotent=False,
    ),
    ToolShape(
        name='rehearse_downloads_pause',
        reach=Reach.REHEARSAL,
        target='downloads-pause',
        capability='/api/actions/downloads-pause',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'required': [], 'additionalProperties': False},
        resource=None,
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='downloads_pause',
        reach=Reach.ACTION,
        target='downloads-pause',
        capability='/api/actions/downloads-pause',
        parameters=('offer',),
        input_schema={'type': 'object',
                      'properties': {'offer': {'type': 'string'}},
                      'required': ['offer'],
                      'additionalProperties': False},
        resource=None,
        read_only=False,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='rehearse_downloads_resume',
        reach=Reach.REHEARSAL,
        target='downloads-resume',
        capability='/api/actions/downloads-resume',
        parameters=(),
        input_schema={'type': 'object', 'properties': {}, 'required': [], 'additionalProperties': False},
        resource=None,
        read_only=True,
        destructive=False,
        idempotent=True,
    ),
    ToolShape(
        name='downloads_resume',
        reach=Reach.ACTION,
        target='downloads-resume',
        capability='/api/actions/downloads-resume',
        parameters=('offer',),
        input_schema={'type': 'object',
                      'properties': {'offer': {'type': 'string'}},
                      'required': ['offer'],
                      'additionalProperties': False},
        resource=None,
        read_only=False,
        destructive=False,
        idempotent=True,
    ),
)
"""Each tool, reads first in the order the contract lists them, then the actions a key may call."""
